concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  linux_lint_python_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - uses: cachix/install-nix-action@e17a164a729f3f908f3997516f02ecaba2b9c201
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@f5f67badd061acb62b5c6e25e763572ca8317004
        with:
          name: vuln-management-api
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#lintPython
  linux_test_python_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - uses: cachix/install-nix-action@e17a164a729f3f908f3997516f02ecaba2b9c201
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@f5f67badd061acb62b5c6e25e763572ca8317004
        with:
          name: vuln-management-api
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix run .#testPython

name: dev
permissions: read-all
on:
  pull_request:
    branches: [main]
